/*yerr 2015-
* */
var modelChoiceService=angular.module('modelChoice.service',[])
modelChoiceService.service('dataservice',function(){
    var dataservice=[
        {
            id:'002',
            modelType:'workOrderModel',
            maintenanceHistory:[{ customerState:'一辆宝骏560智能手动挡汽车，变速箱故障灯点亮车辆无法行驶,同时仪表不显示挡位，请阅读工单后点击下一步按钮。', ResultOrReson:'', program:''}],
            item:'',
            history:'',
            btn:'',
            head_title:'管理系统 > 维修订单 > 维修单-20161226013',
            tips:'一辆宝骏560智能手动挡汽车，变速箱故障灯点亮车辆无法行驶同时仪表不显示挡位。请阅读工单后，点击下一步按钮。',
            bIsArrowNextShow:true,
            audioUrl:[
                'audio/002.mp3'
            ],
            audioIndex: 'audio/001.mp3'
        },
        {
            id:'003',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'了解故障信息后，您下一步的诊断步骤是什么？',
            chooses:[
                '视觉检查',
                '症状确认',
                '故障分析',
                '故障诊断'
            ],
            answer:"b",
            answerTrue:'正确，确定客户描述的故障症状是诊断流程的第一步，目的是验证客户所描述的故障症状是否准确。',
            answerFalse:'不正确，请重新选择!',
            svgimg:'',
            bgimg:'',
            bIsArrowNextShow:false,
            audioUrl:[
                'audio/003.mp3'
            ],
            View_Profile:false
        },
        {
            id:'004',
            modelType:'horiChoiceModel',
            answer:"b",
            tips:'下面将要对维修工单中所描述的故障现象进行确认，请选择需要进入的场景。',
            tips2:'[说明：请选择“车辆内饰” 进入]',
            audioSrc:[
                'audio/004.mp3'
            ],
            
        },
        {//----------------------------
            id:'005',
            modelType:'005',
            audioUrl:[
                'audio/005.mp3'
            ]
        },
        {
            id:'006',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'对当前故障现象描述正确的是哪项？',
            chooses:[
                '变速箱挡杆被锁止无法移动',
                '挂入任何挡位仪表都显示空挡',
                '发动机无法启动',
                '车辆不显示挡位，且不能行驶'
            ],
            answer:"d",
            answerTrue:'正确。',
            answerFalse:'不正确，请重新选择。',
            svgimg:'',
            bgimg:'',
            audioUrl:[
                'audio/006.mp3'
            ],
            View_Profile:false
        },
        {
            id:'007',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'已经确定了故障症状， 在接下来的诊断中您将要做什么?请选择您认为正确的操作。',
            chooses:[
                '视觉检查',
                '故障诊断',
                '初步检查',
                '故障维修'
            ],
            answer:"c",
            answerTrue:'正确，您应该对车辆进行初步检查，以获取故障的基本信息。',
            answerFalse:'不正确，请重新选择!',
            svgimg:'',
            bgimg:'',
            bIsArrowNextShow:false,
            audioUrl:[
                'audio/007.mp3'
            ],
            View_Profile:false
        },
        {//------------------------
            id:'008',
            modelType:'008'
        },
        {
            id:'009',
            modelType:'horiChoiceModel',
            answer:"b",
            tips:'在初步检查过程中需要读取故障代码，请选择相应场景进入。',
            tips2:'[说明：请选择“车辆内饰” 进入]',
            audioSrc:[
                'audio/009.mp3'
            ]
        },
        {//-------------------------------
            id: '010',
            modelType: '010',
            tips:'请使用诊断仪对车辆进行故障码读取。',
        },
        {//------------------------------------
            id:'011',
            modelType:'workOrderModel',
            maintenanceHistory:[],
            item:[],
            history:'yes',
            btn:'',
            btntText:'返回',
            head_title:'管理系统 > 维修历史',
            tips:'维修历史中没有此故障码的相关记录，接下来需要查询服务通告有无相关内容。请点击下一步按钮。',
            audioUrl:[
                'audio/011.mp3'
            ]
        },

        {
            id:'012',
            modelType:'vertChoiceModel',
            description: [
                '',
                '',
                ''
            ],
            tips:'服务通告中没有相关的内容，请点击按钮进入下一界面。'
        },

        {
            id:'013',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'在完成了初步检查后，下一步应进行的诊断步骤是什么？',
            chooses:[
                '视觉检查',
                '故障诊断',
                '故障分析',
                '故障维护'
            ],
            answer:"c",
            answerTrue:'回答正确。',
            answerFalse:'不正确，请重新选择!',
            svgimg:'',
            bgimg:'',
            View_Profile:false
        },

        {
            id:'014',
            modelType:'horiChoiceModel',
            answer:"e",
            tips:'信息列表中的哪个资源能够帮助你进行故障分析，请点击进入。',
            tips2:'[说明：请选择“维修资料” 进入]',
            audioSrc:[
                'audio/014.mp3'
            ]
        },
        {
            id:'015',
            modelType:'vertChoiceModel',
            description: [
                'P091000',
                'P090000',
                'P092000'
            ],
            answer:"b",
            tips:'请选择当前车辆出现的故障代码，然后了解相关故障信息。'
        },
        {
            id:'016',
            modelType:'modelBgImg',
            bgimg:['images/svg/1940-1931-28-29-30-31.png'],
            tips:'请仔细阅读这个故障码的详细资料，这些资料能够帮助你快速分析故障原因。阅读完成后，请点击“下一步”按钮。',
            View_Profile:true
        },
        {
            id:'017',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'根据资料，在电机非通电时，关于故障码设置条件哪些说法是错误的？',
            chooses:[
                '对电源短路故障 ：电机端子电压较大的一方比对电源短路判定电压大',
                '对地短路故障 ：电机端子电压较小的一方比对地短路判定电压小',
                '电机端子电压的差比断路判定电压小',
                '对地短路判定电压 ：电机端子～ GND间的电压低于2.1V（TYP）时检出'
            ],
            answer:"c",
            answerTrue:'非常好，请进行下一步。',
            answerFalse:'不正确，请重新选择。',
            bgimg:'',
            svgimg:'images/svg/1940-1931-28-29-30-31.png',
            audioUrl:[
                'audio/017.mp3'
            ],
            View_Profile:true
        },
        {
            id:'018',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'离合器电机的控制信号属于哪种类型？',
            chooses:[
                '调幅信号',
                '负触发信号',
                '占空比信号',
                '频率信号'
            ],
            answer:"c",
            answerTrue:'非常好，请进行下一步。',
            answerFalse:'答错了，请重新选择。',
            bgimg:'',
            svgimg:'images/svg/1940-1931-28-29-30-31.png',
            audioUrl:[
                'audio/018.mp3'
            ],
            View_Profile:true
        },
        {
            id:'019',
            modelType:'modelMultiple',
            description:'诊断策略检查',
            title:'如果离合器电机驱动回路出现异常其具体的故障现象是什么？(多选)',
            chooses:[
                '行驶中变速会切换至空挡',
                '车辆失去行驶能力',
                '车辆只能在1挡行驶',
                '行驶中限制车辆升入4挡和5挡'
            ],
            answer:"A，B，",
            answerTrue:'非常好，请进行下一步。',
            answerFalse:'答错了，请重新选择。',
            bgimg:'',
            svgimg:'images/svg/1940-1931-28-29-30-31.png',
            audioUrl:[
                'audio/019.mp3'
            ],
            View_Profile:true
        },
        {
            id:'020',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'离合器电机至TCM之间由几段线束组成？',
            chooses:[
                '4段',
                '3段',
                '2段',
                '1段'
            ],
            answer:"c",
            answerTrue:'正确 ，做的很好。',
            answerFalse:'不正确，请重新选择!',
            svgimg:'images/svg/1940-1931-28-29-30-31.png',
            bgimg:'',
            audioUrl:[
                'audio/020.mp3'
            ],
            View_Profile:true
        },
        {
            id:'021',
            modelType:'modelMultiple',
            description:'诊断策略检查',
            title:'结合维修资料，下面叙述正确的是哪项？(多选)',
            chooses:[
                'TCM检测到电机驱动回路异常将切断电机电源',
                '离合器电机的正反转由TCM来控制',
                'TCM线束接地点虚接可以导致当前故障和多个故障码',
                '离合器电机电流大于61.25A时将设置故障码'
            ],
            answer:"A，B，C，D，",
            answerTrue:'做的非常好!',
            answerFalse:'错误，请重新选择!',
            svgimg:'images/svg/1940-1931-28-29-30-31.png',
            bgimg:'',
            audioUrl:[
                'audio/021.mp3'
            ],
            View_Profile:true
        },
        {
            id:'022',
            modelType:'modelMultiple',
            description:'诊断策略检查',
            title:'下面哪种情况说明离合器电机出现故障？(多选)',
            chooses:[
                '电机正负端子之间电阻大于1欧姆',
                '电机正负端子之间电阻小于1欧姆',
                '电机正负端子分别对壳体电阻大于10千欧姆',
                '电机正负端子分别对壳体电阻小于10千欧姆'
            ],
            answer:"A，D，",
            answerTrue:'做的非常好!',
            answerFalse:'错误，请重新选择!',
            svgimg:'images/svg/1940-1931-28-29-30-31.png',
            bgimg:'',
            audioUrl:[
                'audio/022.mp3'
            ],
            View_Profile:true
        },
        {
            id:'023',
            modelType:'modelMultiple',
            description:'诊断策略检查',
            title:'通过对资料的分析，你认为哪些问题可以导致当前故障现象的发生？(多选)',
            chooses:[
                '离合器电机故障',
                '离合器电机至TCM之间线束短路或断路',
                'TCM本体故障',
                'TCM线束搭铁'
            ],
            answer:"A，B，C，D，",
            answerTrue:'做的非常好!',
            answerFalse:'错误，请重新选择!',
            svgimg:'images/svg/1940-1931-28-29-30-31.png',
            bgimg:'',
            audioUrl:[
                'audio/023.mp3'
            ],
            View_Profile:true
        },
        {
            id:'024',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'在完成故障分析后下面要进行的诊断步骤是什么？',
            chooses:[
                '视觉检查',
                '故障诊断',
                '故障分析',
                '故障维修'
            ],
            answer:"a",
            answerTrue:'做的非常好!',
            answerFalse:'错误，请重新选择!',
            svgimg:'',
            bgimg:'',
            audioUrl:[
                'audio/024.mp3'
            ],
            View_Profile:false
        },

        {
            id:'025',
            modelType:'modelMultiple',
            description:'诊断策略检查',
            title:'通过上面的学习，您认为需要视觉检查的部位有哪些？(多选)',
            chooses:[
                'TCM模块',
                '发动机控制模块',
                '离合器电机和插头',
                'TCM模块搭铁'
            ],
            answer:"A，C，D，",
            answerTrue:'正确 ，非常好。',
            answerFalse:'不正确，请重新选择!',
            svgimg:'',
            bgimg:'',
            View_Profile:false
            // audioUrl:[
            //     'audio/025.mp3'
            // ]
        },
        {//----------------------------
            id:'026',
            modelType:'horiChoiceModel',
            answer:"e",
            tips:'选择合适的选项，学习相关资料，了解可疑部件在车上的位置和拆装方法。',
            tips2:'[说明：请选择“维修资料” 进入]',
            audioSrc:[
                'audio/009.mp3'
            ]
        },
        {
            id:'027',
            modelType:'modelBgImg',
            bgimg:['images/svg/9-10.png','images/svg/27-31.png'],
            tips:'完成资料学习后点击下一步按钮进行外观的检查。',
            View_Profile:true
        },
        {

            id:'028',
            modelType:'028'
        },
        {
            id:'029',
            modelType:'029'
        },
        {

            id:'030',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'如果在外观检查中,未发现部件存在异常情况，下一步的诊断策略是什么？',
            chooses:[
                '故障诊断',
                '故障维修',
                '症状确认',
                '修复确认'
            ],
            answer:"a",
            answerTrue:'做的非常好。',
            answerFalse:'不正确。',
            svgimg:'',
            audioUrl:[
                'audio/030.mp3'
            ],
            View_Profile:false
        },

        {
            id:'031',
            modelType:'horiChoiceModel',
            answer:"e",
            tips:'在故障诊断前，请查阅故障相关资料，请选择正确的选项。',
            tips2:'[说明：请选择“维修资料” 进入]',
            audioSrc:[
                'audio/031.mp3'
            ]
        },
        {
            id:'032',
            modelType:'modelBgImg',
            bgimg:['images/svg/1940-1931.png'],
            tips:'请仔细阅读维修资料，然后点击下一步对故障可疑位置进行测量。',
            View_Profile:true
        },

        {
            id:'033',
            modelType:'033',
            audioUrl:[
                'audio/033.mp3'
            ]
        },
        {
            id:'034',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'通过对TCM X3 插头的测量，你可以分析出什么结果？',
            chooses:[
                'TCM X3插头5、6号端子之间电路无异常',
                'TCM X3插头5、6号端子之间线路对地短路',
                'TCM X3插头5、6号端子之间线路对电源短路',
                'TCM X3插头5、6号端子之间线路断路'
            ],
            answer:"b",
            answerTrue:'正确。',
            answerFalse:'不正确。',
            svgimg:'images/svg/1940-1931.png',
            audioUrl:[
                'audio/034.mp3'
            ],
            View_Profile:true
        },
        {
            id:'035',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'根据维修资料，离合器电机正负极分别经过X102插头的哪几个端子？',
            chooses:[
                'X102线束插头的1和8号端子',
                'X102线束插头的26和39号端子',
                'X102线束插头的26和37号端子',
                'X102线束插头的29和36号端子'
            ],
            answer:"d",
            answerTrue:'正确。',
            answerFalse:'不正确。',
            svgimg:'images/svg/1940-1931-212.png',
            audioUrl:[
                'audio/035.mp3'
            ],
            View_Profile:true
        },
        {
            id:'036',
            modelType:'036',
        },
        {
            id:'037',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'通过上面的测量，你可以得出什么结果？',
            chooses:[
                '电机正负端子与X102插头之间电路断路',
                '电机正负端子与X102插头之间电路正常',
                '电机正负端子与X102插头之间对地短路',
                '电机正负端子与X102插头之间对电源短路'
            ],
            answer:"b",
            answerTrue:'正确。',
            answerFalse:'不正确。',
            svgimg:'images/svg/1940-1931-212.png',
            audioUrl:[
                'audio/037.mp3'
            ],
            View_Profile:true
        },
        {
            id:'038',
            modelType:'038',
        },
        {
            id:'039',
            modelType:'modelMultiple',
            description:'诊断策略检查',
            title:'通过对上面测量结果的分析，下面回答正确的是什么？请选择！(多选)',
            chooses:[
                '5-36号端子之间线路存在对电源短路的情况',
                '6-29号端子之间线路没有异常情况',
                '5-36号端子之间线路存在对地短路的情况',
                '6-29号端子之间线路存在对电源短路的情况'
            ],
            answer:"B，C，",
            answerTrue:'正确。',
            answerFalse:'不正确,请重新选择！',
            svgimg:'images/svg/1940-1931-212.png',
            audioUrl:[
                'audio/039.mp3'
            ],
            View_Profile:true
        },
        {
            id:'040',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'根据维修资料，X102插座至TCM X3之间由哪根线束连接？',
            chooses:[
                '换挡电机线束',
                '变速箱线束',
                'X102发动机线束',
                'X101发动机线束'
            ],
            answer:"b",
            answerTrue:'做的非常好。',
            answerFalse:'错误，请重新选择!',
            svgimg:'images/svg/1940-1931.png',
            bgimg:'',
            View_Profile:true
        },
        {
            id:'041',
            modelType:'workOrderModel',
            maintenanceHistory:[{ customerState:'一辆宝骏560智能手动挡汽车，变速箱故障灯点亮车辆无法行驶,同时仪表不显示挡位，请阅读工单后点击下一步按钮。', ResultOrReson:'', program:''}],
            item:'',
            history:'',
            btn:'yes',
            btntText:'提交',
            fillIn:true,
            head_title:'管理系统 > 维修订单 > 维修单-20161226013',
            tips:'请根据检测结果填写工单',
            bIsArrowNextShow:true,
        },
        {
            id:'042',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'在确定故障部位后，下一步应该如何操作？',
            chooses:[
                '初步检查',
                '故障诊断',
                '故障维修',
                '修复确认'
            ],
            answer:"c",
            answerTrue:'正确，进入下一步。',
            answerFalse:'不正确，请重新选择!',
            svgimg:'',
            bgimg:'',
            View_Profile:false
        },
        {
            id:'043',
            modelType:'043'
        },
        {
            id:'044',
            modelType:'choiceModel',
            description:'诊断策略检查',
            title:'故障零件已经更换，接下来，您该如何验证您的维修成果？',
            chooses:[
                '测量故障线路是否恢复正常',
                '验证车辆故障现象是否消失',
                '使用解码器清除故障码后交车',
                '交车给客户然后等待客户反馈 '
            ],
            answer:"b",
            answerTrue:'做的非常好。',
            answerFalse:'不正确。',
            svgimg:'',
            View_Profile:false
        },
        {
            id:'045',
            modelType:'045'
        },
        {
            id:'046',
            modelType:'modelMultiple',
            description:'诊断策略检查',
            title:'根据上面对车辆测试，回答正确选项。(多选)',
            chooses:[
                '车辆可以升入到最高挡位',
                '离合器可以正常结合',
                '车辆蠕动功能正常',
                '故障灯消失'
            ],
            answer:"A，B，C，D，",
            answerTrue:'做的非常好。',
            answerFalse:'不正确。',
            svgimg:'',
            View_Profile:false
        },
        {
            id:'047',
            modelType:'047',
            audioUrl:[
                'audio/050.mp3'
            ]
        },
        {
            id:'048',
            modelType:'workOrderModel',
            maintenanceHistory:[{ customerState:'一辆宝骏560智能手动挡汽车，变速箱故障灯点亮车辆无法行驶,同时仪表不显示挡位，请阅读工单后点击下一步按钮。', ResultOrReson:'X102 36号端子 至TCM X3  5号端子之间线束存在对地短路。', program:''}],
            item:'',
            history:'',
            btn:'yes',
            btntText:'提交',
            fillIn:true,
            head_title:'管理系统 > 维修订单 > 维修单-20161226013',
            tips:'请根据故障维修情况填写工单。',
            bIsArrowNextShow:true,
        }
    ];
    return dataservice;
});
/*
* yerr service End
* */